### ISSUE TITLE
how to host it on repl it? 

### ISSUE THREAD

**Issue by unknown821** [Rup-1234/Discord-Chatbot#3]
hello ace.
i am getting this error in replit (i dont know anything about coding;-;) pls help

console log-
`npm start

> brain-chatbot@1.0.0 start /home/runner/Discord-Chatbot
> node index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /home/runner/Discord-Chatbot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Discord-Chatbot/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Discord-Chatbot/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brain-chatbot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brain-chatbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-11T14_46_10_520Z-debug.log
exit status 1
 `

**Comment by RupCodes** [comment]
Hey, looks like you're facing issues with installing modules
Consider joining support server for help
https://discord.gg/tzjssZU2
